trigger: example_form
title: Example form
description: Example of how to use a form
steps:
- type: form
  style: embedded
  body:
  - type: dropdown
    attributes:
      label: Color
      description: What's the status of your project?
      options:
      - label: 游릭 Green
        value: 游릭
      - label: 游리 Yellow
        value: 游리
      - label: 游댮 Red
        value: 游댮
  - type: textarea
    attributes:
      label: Details
      description: What should the team know about the status of your project?
      placeholder: Recent achievements, blockers, requests for help, etc.
  actions:
    submit: "Create"
    cancel: "Discard"
- type: fill
  template: |-
    Color: {{ data.Color }}
    Details: {{ data.Details }}
